services:
  db:
    image: postgres:15-alpine
    container_name: transacao_consumer_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data_consumer:/var/lib/postgresql/data_consumer
    ports:
      - "5433:5432"
