services:
  db:
    image: postgres:15-alpine
    container_name: transacao_consumer_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data_consumer:/var/lib/postgresql/data_consumer
    ports:
      - "5433:5432"

#services:
#  keycloak:
#    image: quay.io/keycloak/keycloak:latest
#    command: start-dev
#    ports:
#      - "8080:8080"
#    environment:
#      KC_BOOTSTRAP_ADMIN_USERNAME: admin
#      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
#      KC_DB: postgres
#      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
#      KC_DB_USERNAME: admin
#      KC_DB_PASSWORD: admin
#    depends_on:
#       db:
#         condition: service_healthy
#
#  db:
#    image: postgres:latest
#    volumes:
#    - ./.docker/data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: keycloak
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#    healthcheck:
#      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d postgres'"]
#      interval: 10s
#      timeout: 10s
#      retries: 5